/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exypnos;

import com.sun.webkit.perf.PerfLogger;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JList;
/**
 *
 * @author Afif Raihan
 */
public class GUI_Admin extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Admin
     */
    public GUI_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelHaloAdmin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanelChange = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        btnLihatSiswa = new javax.swing.JButton();
        btnLihatTentor = new javax.swing.JButton();
        btnLihatMapel = new javax.swing.JButton();
        btnLihatKelas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taHasil = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        updateMapel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listMapelUpdate = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taDeskripsiMapelUpdate = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfUpdateMapelNama = new javax.swing.JTextField();
        tfUpdateBabMapel = new javax.swing.JTextField();
        tfUpdateKkmMapel = new javax.swing.JTextField();
        btnUpdateMapel = new javax.swing.JButton();
        deleteMapel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        listMapelDelete = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        taDeskripsiMapelDelete = new javax.swing.JTextArea();
        btnDeleteMapel = new javax.swing.JButton();
        createMapel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfNamaMapelCreate = new javax.swing.JTextField();
        tfJumlahBabCreate = new javax.swing.JTextField();
        tfKkmCreate = new javax.swing.JTextField();
        btnDaftar = new javax.swing.JButton();
        labelStatus = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listMapelCreate = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDeskripsiMapelCreate = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanelHaloAdmin.setBackground(new java.awt.Color(44, 120, 115));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/exypnos1.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(194, 232, 206));
        jLabel2.setText("Halo Admin");

        btnLogout.setBackground(new java.awt.Color(204, 0, 0));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHaloAdminLayout = new javax.swing.GroupLayout(jPanelHaloAdmin);
        jPanelHaloAdmin.setLayout(jPanelHaloAdminLayout);
        jPanelHaloAdminLayout.setHorizontalGroup(
            jPanelHaloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHaloAdminLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(221, 221, 221)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(34, 34, 34))
        );
        jPanelHaloAdminLayout.setVerticalGroup(
            jPanelHaloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHaloAdminLayout.createSequentialGroup()
                .addGroup(jPanelHaloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHaloAdminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelHaloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHaloAdminLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );

        jPanelChange.setLayout(new java.awt.CardLayout());

        jPanelMenu.setBackground(new java.awt.Color(111, 185, 143));

        btnLihatSiswa.setBackground(new java.awt.Color(44, 120, 115));
        btnLihatSiswa.setText("Lihat Siswa");
        btnLihatSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatSiswaActionPerformed(evt);
            }
        });

        btnLihatTentor.setBackground(new java.awt.Color(44, 120, 115));
        btnLihatTentor.setText("Lihat Tentor");
        btnLihatTentor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatTentorActionPerformed(evt);
            }
        });

        btnLihatMapel.setBackground(new java.awt.Color(44, 120, 115));
        btnLihatMapel.setText("Lihat Mata Pelajaran");
        btnLihatMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatMapelActionPerformed(evt);
            }
        });

        btnLihatKelas.setBackground(new java.awt.Color(44, 120, 115));
        btnLihatKelas.setText("Lihat Kelas");

        taHasil.setEditable(false);
        taHasil.setBackground(new java.awt.Color(202, 252, 224));
        taHasil.setColumns(20);
        taHasil.setRows(30);
        taHasil.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Hasil"));
        jScrollPane1.setViewportView(taHasil);

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLihatKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLihatMapel, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                            .addComponent(btnLihatTentor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLihatSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addComponent(btnLihatKelas)
                        .addGap(18, 18, 18)
                        .addComponent(btnLihatMapel)
                        .addGap(18, 18, 18)
                        .addComponent(btnLihatTentor)
                        .addGap(27, 27, 27)
                        .addComponent(btnLihatSiswa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelChange.add(jPanelMenu, "card2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        jPanelChange.add(jPanel2, "card3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        jPanelChange.add(jPanel5, "card5");

        jScrollPane4.setViewportView(listMapelUpdate);

        jLabel9.setText("List Mata Pelajaran");

        jLabel10.setText("Deskripsi");

        taDeskripsiMapelUpdate.setColumns(20);
        taDeskripsiMapelUpdate.setRows(5);
        jScrollPane5.setViewportView(taDeskripsiMapelUpdate);

        jLabel11.setText("Update Mata Pelajaran");

        jLabel12.setText("Nama Mata Pelajaran");

        jLabel13.setText("Jumlah Bab");

        jLabel14.setText("KKM");

        btnUpdateMapel.setText("Update");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfUpdateMapelNama)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfUpdateBabMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfUpdateKkmMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 371, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdateMapel)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfUpdateMapelNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfUpdateBabMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfUpdateKkmMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnUpdateMapel)
                .addContainerGap())
        );

        javax.swing.GroupLayout updateMapelLayout = new javax.swing.GroupLayout(updateMapel);
        updateMapel.setLayout(updateMapelLayout);
        updateMapelLayout.setHorizontalGroup(
            updateMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateMapelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(updateMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(updateMapelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        updateMapelLayout.setVerticalGroup(
            updateMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateMapelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(updateMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(updateMapelLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanelChange.add(updateMapel, "card6");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel15.setText("Delete Mata Pelajaran");

        jScrollPane6.setViewportView(listMapelDelete);

        taDeskripsiMapelDelete.setColumns(20);
        taDeskripsiMapelDelete.setRows(5);
        jScrollPane7.setViewportView(taDeskripsiMapelDelete);

        btnDeleteMapel.setText("Delete");
        btnDeleteMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMapelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteMapelLayout = new javax.swing.GroupLayout(deleteMapel);
        deleteMapel.setLayout(deleteMapelLayout);
        deleteMapelLayout.setHorizontalGroup(
            deleteMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteMapelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deleteMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteMapelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDeleteMapel)))
                .addContainerGap())
        );
        deleteMapelLayout.setVerticalGroup(
            deleteMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteMapelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(deleteMapelLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteMapel)
                        .addGap(0, 154, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelChange.add(deleteMapel, "card7");

        createMapel.setBackground(new java.awt.Color(111, 185, 143));

        jPanel3.setBackground(new java.awt.Color(44, 120, 115));

        jLabel4.setText("Buat Mata pelajaran Baru");

        jLabel5.setText("Nama Mata Pelajaran");

        jLabel6.setText("Jumlah Bab");

        jLabel7.setText("KKM");

        tfNamaMapelCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaMapelCreateActionPerformed(evt);
            }
        });

        tfJumlahBabCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahBabCreateActionPerformed(evt);
            }
        });

        tfKkmCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKkmCreateActionPerformed(evt);
            }
        });

        btnDaftar.setText("Daftar");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        labelStatus.setText("Status");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNamaMapelCreate)
                            .addComponent(tfJumlahBabCreate)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tfKkmCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 167, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNamaMapelCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfJumlahBabCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfKkmCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnDaftar)
                .addGap(18, 18, 18)
                .addComponent(labelStatus)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(44, 120, 115));

        jLabel8.setText("Daftar Semua Mata Pelajaran");

        jScrollPane2.setViewportView(listMapelCreate);

        taDeskripsiMapelCreate.setEditable(false);
        taDeskripsiMapelCreate.setColumns(20);
        taDeskripsiMapelCreate.setRows(5);
        jScrollPane3.setViewportView(taDeskripsiMapelCreate);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        jLabel3.setBackground(new java.awt.Color(111, 185, 143));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel3.setText("Create dan View Mata Pelajaran");

        javax.swing.GroupLayout createMapelLayout = new javax.swing.GroupLayout(createMapel);
        createMapel.setLayout(createMapelLayout);
        createMapelLayout.setHorizontalGroup(
            createMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createMapelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createMapelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createMapelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        createMapelLayout.setVerticalGroup(
            createMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createMapelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(createMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelChange.add(createMapel, "card4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHaloAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelHaloAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(558, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 90, Short.MAX_VALUE)
                    .addComponent(jPanelChange, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLihatSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatSiswaActionPerformed
        // TODO add your handling code here:
        jPanelChange.removeAll();
        jPanelChange.add(createMapel);
        jPanelChange.repaint();
        jPanelChange.revalidate();
    }//GEN-LAST:event_btnLihatSiswaActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        jPanelChange.removeAll();
        jPanelChange.add(jPanelMenu);
        resetView();
        jPanelChange.repaint();
        jPanelChange.revalidate();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void tfJumlahBabCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahBabCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJumlahBabCreateActionPerformed

    private void tfKkmCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKkmCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKkmCreateActionPerformed

    private void tfNamaMapelCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaMapelCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaMapelCreateActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void btnLihatTentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatTentorActionPerformed
        // TODO add your handling code here:
        jPanelChange.removeAll();
        jPanelChange.add(updateMapel);
        jPanelChange.repaint();
        jPanelChange.revalidate();
    }//GEN-LAST:event_btnLihatTentorActionPerformed

    private void btnLihatMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatMapelActionPerformed
        // TODO add your handling code here:
        jPanelChange.removeAll();
        jPanelChange.add(deleteMapel);
        jPanelChange.repaint();
        jPanelChange.revalidate();
    }//GEN-LAST:event_btnLihatMapelActionPerformed

    private void btnDeleteMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMapelActionPerformed

    
    
    public JButton getBtnLihatKelas(){
        return btnLihatKelas;
    }
    public JButton getBtnLihatSiswa(){
        return btnLihatSiswa;
    }
    public JButton getBtnLihatMapel(){
        return btnLihatMapel;
    }
    public JButton getBtnLihatTentor(){
        return btnLihatTentor;
    }
    public JButton getBtnDaftar(){
        return btnDaftar;
    }
    public JButton getBtnUpdateMapel(){
        return btnUpdateMapel;
    }
    public JButton getBtnDeleteMapel(){
        return btnDeleteMapel;
    }
        
    public void addActionListener(ActionListener al){
        btnLihatKelas.addActionListener(al);
        btnLihatMapel.addActionListener(al);
        btnLihatSiswa.addActionListener(al);
        btnLihatTentor.addActionListener(al);
        btnLogout.addActionListener(al);
        btnDaftar.addActionListener(al);
        btnUpdateMapel.addActionListener(al);
        btnDeleteMapel.addActionListener(al);
    }
    
    public void addMouseAdapter(MouseAdapter ma){
        listMapelCreate.addMouseListener(ma);
        listMapelUpdate.addMouseListener(ma);
        listMapelDelete.addMouseListener(ma);
    }
    
    public void resetView(){
        tfNamaMapelCreate.setText("");
        tfJumlahBabCreate.setText("");
        tfKkmCreate.setText("");
        taDeskripsiMapelCreate.setText("");
        taDeskripsiMapelUpdate.setText("");
        taDeskripsiMapelDelete.setText("");
        tfUpdateBabMapel.setText("");
        tfUpdateKkmMapel.setText("");
        tfUpdateMapelNama.setText("");
    }
    
    
    
    public void tampilkanHasil(String s){
        taHasil.setText(s);
    }
//////// create MAPEL    
    public void setListMapel (String[] listKelasid){
        listMapelCreate.setListData(listKelasid);
    }
    public JList getListMapel(){
        return listMapelCreate;
    }  
    public String getSelectedMapel (){
        return listMapelCreate.getSelectedValue();
    }
    
    public String getNamaMapel(){
        return tfNamaMapelCreate.getText();
    }    
    public int getJumlahBab(){
        return Integer.parseInt(tfJumlahBabCreate.getText());
    } 
    public int getKkm(){
        return Integer.parseInt(tfKkmCreate.getText());
    } 
    public void setMapelString(String s){
        taDeskripsiMapelCreate.setText(s);
    }

//////   UPDATE MAPEL   
    public void setListMapelUpdate (String[] listKelasid){
        listMapelUpdate.setListData(listKelasid);
    }
    public JList getListMapelUpdate(){
        return listMapelUpdate;
    }  
    public String getSelectedMapelUpdate(){
        return listMapelUpdate.getSelectedValue();
    }
    
    public String getNamaMapelUpdate(){
        return tfUpdateMapelNama.getText();
    }    
    public int getJumlahBabUpdate(){
        return Integer.parseInt(tfUpdateBabMapel.getText());
    } 
    public int getKkmUpdate() {
        return Integer.parseInt(tfUpdateKkmMapel.getText());
    }
    public void setUpdateMapelString(String s) {
        taDeskripsiMapelUpdate.setText(s);
    }
////// Delete Mapel
    public void setListMapelDelete (String[] listKelasid){
        listMapelDelete.setListData(listKelasid);
    }
    public JList getListMapelDelete(){
        return listMapelDelete;
    }  
    public String getSelectedMapelDelete(){
        return listMapelDelete.getSelectedValue();
    }
    public void setDeleteMapelString(String s) {
        taDeskripsiMapelDelete.setText(s);
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnDeleteMapel;
    private javax.swing.JButton btnLihatKelas;
    private javax.swing.JButton btnLihatMapel;
    private javax.swing.JButton btnLihatSiswa;
    private javax.swing.JButton btnLihatTentor;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateMapel;
    private javax.swing.JPanel createMapel;
    private javax.swing.JPanel deleteMapel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelChange;
    private javax.swing.JPanel jPanelHaloAdmin;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JList<String> listMapelCreate;
    private javax.swing.JList<String> listMapelDelete;
    private javax.swing.JList<String> listMapelUpdate;
    private javax.swing.JTextArea taDeskripsiMapelCreate;
    private javax.swing.JTextArea taDeskripsiMapelDelete;
    private javax.swing.JTextArea taDeskripsiMapelUpdate;
    private javax.swing.JTextArea taHasil;
    private javax.swing.JTextField tfJumlahBabCreate;
    private javax.swing.JTextField tfKkmCreate;
    private javax.swing.JTextField tfNamaMapelCreate;
    private javax.swing.JTextField tfUpdateBabMapel;
    private javax.swing.JTextField tfUpdateKkmMapel;
    private javax.swing.JTextField tfUpdateMapelNama;
    private javax.swing.JPanel updateMapel;
    // End of variables declaration//GEN-END:variables
}
