/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JList;

/**
 *
 * @author farell
 */
public class GUI_MenuTentor extends javax.swing.JFrame {

    /**
     * Creates new form GUI_MenuTentor
     */
    public GUI_MenuTentor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Latar = new java.awt.Panel();
        panelHeader = new javax.swing.JPanel();
        LabelWelcomTentor = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        Utama = new java.awt.Panel();
        Menu = new java.awt.Panel();
        btnMenuLihatKelas = new javax.swing.JButton();
        btnMenuBuatMtr = new javax.swing.JButton();
        btnMenuTampilkanMtr = new javax.swing.JButton();
        btnMenuUbahMtr = new javax.swing.JButton();
        btnMenuHapusMtr = new javax.swing.JButton();
        btnMenuUbahProfile = new javax.swing.JButton();
        DaftarKelasSiswa = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListKelas_DaftarKelasSiswa = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDeskripsiKelasTentor = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Buat_materi = new java.awt.Panel();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label10 = new java.awt.Label();
        label5 = new java.awt.Label();
        tfBuatMateri_NamaMateri = new javax.swing.JTextField();
        tfBuatMateri_JmlBahasan = new javax.swing.JTextField();
        label7 = new java.awt.Label();
        btnBuatMateri = new javax.swing.JButton();
        list1 = new java.awt.List();
        label9 = new java.awt.Label();
        list2 = new java.awt.List();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListKelas_BuatMateri = new javax.swing.JList<>();
        TampilkanMateri = new java.awt.Panel();
        label6 = new java.awt.Label();
        label8 = new java.awt.Label();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListKelas_ViewMateri = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        taDeskripsiViewMateri = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        UpdateMateri = new java.awt.Panel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfUpdateMateri_NamaMateriBaru = new javax.swing.JTextField();
        tfUpdateMateri_jmlBahasanBaru = new javax.swing.JTextField();
        btnUpdateMateri = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ListMateri_UpdateMateri = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        ListKelas_UpdateMateri = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DeleteMateri = new java.awt.Panel();
        jLabel15 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jScrollPane10 = new javax.swing.JScrollPane();
        ListKelas_DeleteMateri = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        ListMateri_DeleteMateri = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnDeleteMateri = new javax.swing.JButton();
        UpdateDataTentor = new java.awt.Panel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        taDeskripsiUpdateProfile = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        tfUpdateProfile_NamaTentor = new javax.swing.JTextField();
        btnUpdateDataPribadi = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("GUI_TENTOR"); // NOI18N

        Latar.setBackground(new java.awt.Color(111, 185, 143));

        panelHeader.setBackground(new java.awt.Color(44, 120, 115));
        panelHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        LabelWelcomTentor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelWelcomTentor.setForeground(new java.awt.Color(111, 185, 143));
        LabelWelcomTentor.setText("Halo Admin");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/exypnos1.png"))); // NOI18N

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 0));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/rsz_logoutt.png"))); // NOI18N
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setFocusable(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnBack1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/rsz_home.png"))); // NOI18N
        btnBack1.setAlignmentY(0.0F);
        btnBack1.setBorder(null);
        btnBack1.setBorderPainted(false);
        btnBack1.setContentAreaFilled(false);
        btnBack1.setDefaultCapable(false);
        btnBack1.setDisabledSelectedIcon(null);
        btnBack1.setDoubleBuffered(true);
        btnBack1.setFocusable(false);
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelWelcomTentor)
                .addGap(213, 213, 213)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel21))
                            .addComponent(btnBack1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelHeaderLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(LabelWelcomTentor)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Utama.setLayout(new java.awt.CardLayout());

        Menu.setBackground(new java.awt.Color(44, 120, 115));

        btnMenuLihatKelas.setText("Lihat Kelas Dan Siswa");
        btnMenuLihatKelas.setActionCommand("Lihat Kelas ");
        btnMenuLihatKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuLihatKelasActionPerformed(evt);
            }
        });

        btnMenuBuatMtr.setText("Buat Materi");
        btnMenuBuatMtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuBuatMtrActionPerformed(evt);
            }
        });

        btnMenuTampilkanMtr.setText("Tampilkan Materi");
        btnMenuTampilkanMtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuTampilkanMtrActionPerformed(evt);
            }
        });

        btnMenuUbahMtr.setText("Ubah Materi");
        btnMenuUbahMtr.setActionCommand("Perbaharui Materi");
        btnMenuUbahMtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuUbahMtrActionPerformed(evt);
            }
        });

        btnMenuHapusMtr.setText("Hapus Materi");
        btnMenuHapusMtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuHapusMtrActionPerformed(evt);
            }
        });

        btnMenuUbahProfile.setText("Ubah Data Diri");
        btnMenuUbahProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuUbahProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMenuBuatMtr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenuLihatKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMenuUbahMtr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuHapusMtr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnMenuTampilkanMtr, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(btnMenuUbahProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuLihatKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuUbahMtr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuBuatMtr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuHapusMtr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuTampilkanMtr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuUbahProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        Utama.add(Menu, "card2");

        DaftarKelasSiswa.setBackground(new java.awt.Color(44, 120, 115));

        ListKelas_DaftarKelasSiswa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.gray, null, java.awt.Color.darkGray));
        jScrollPane1.setViewportView(ListKelas_DaftarKelasSiswa);

        taDeskripsiKelasTentor.setColumns(20);
        taDeskripsiKelasTentor.setRows(5);
        taDeskripsiKelasTentor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.gray, null, java.awt.Color.darkGray));
        jScrollPane2.setViewportView(taDeskripsiKelasTentor);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("Daftar Kelas Tentor");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("Deskirpsi Kelas");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Daftar Kelas Beserta Siswa");

        javax.swing.GroupLayout DaftarKelasSiswaLayout = new javax.swing.GroupLayout(DaftarKelasSiswa);
        DaftarKelasSiswa.setLayout(DaftarKelasSiswaLayout);
        DaftarKelasSiswaLayout.setHorizontalGroup(
            DaftarKelasSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DaftarKelasSiswaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(DaftarKelasSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(DaftarKelasSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DaftarKelasSiswaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DaftarKelasSiswaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(DaftarKelasSiswaLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DaftarKelasSiswaLayout.setVerticalGroup(
            DaftarKelasSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DaftarKelasSiswaLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DaftarKelasSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DaftarKelasSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                .addContainerGap())
        );

        Utama.add(DaftarKelasSiswa, "card3");

        Buat_materi.setBackground(new java.awt.Color(44, 120, 115));

        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label3.setText("Nama Materi");

        label4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label4.setText("Buat Materi");

        label10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label10.setText("Nama Materi ");

        label5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label5.setText("Jumlah Bahasan");

        tfBuatMateri_NamaMateri.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.black, null, java.awt.Color.darkGray));

        tfBuatMateri_JmlBahasan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.lightGray, null, java.awt.Color.darkGray));

        label7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label7.setText("Sub-Bab");

        btnBuatMateri.setText("Buat");
        btnBuatMateri.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label9.setText("Kelas tersedia");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        ListKelas_BuatMateri.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane4.setViewportView(ListKelas_BuatMateri);

        javax.swing.GroupLayout Buat_materiLayout = new javax.swing.GroupLayout(Buat_materi);
        Buat_materi.setLayout(Buat_materiLayout);
        Buat_materiLayout.setHorizontalGroup(
            Buat_materiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buat_materiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buat_materiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Buat_materiLayout.createSequentialGroup()
                        .addGroup(Buat_materiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Buat_materiLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Buat_materiLayout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(Buat_materiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuatMateri, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Buat_materiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Buat_materiLayout.createSequentialGroup()
                                    .addComponent(tfBuatMateri_JmlBahasan, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfBuatMateri_NamaMateri, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Buat_materiLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Buat_materiLayout.setVerticalGroup(
            Buat_materiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buat_materiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buat_materiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Buat_materiLayout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Buat_materiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Buat_materiLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                            .addGroup(Buat_materiLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))))
                    .addComponent(tfBuatMateri_NamaMateri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(Buat_materiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Buat_materiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(Buat_materiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfBuatMateri_JmlBahasan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106)
                        .addComponent(btnBuatMateri, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        Utama.add(Buat_materi, "card4");

        TampilkanMateri.setBackground(new java.awt.Color(44, 120, 115));

        label6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label6.setForeground(new java.awt.Color(111, 185, 143));
        label6.setText("Tampilkan Materi");

        label8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label8.setText("Kelas Tersedia");

        ListKelas_ViewMateri.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane5.setViewportView(ListKelas_ViewMateri);

        taDeskripsiViewMateri.setColumns(20);
        taDeskripsiViewMateri.setRows(5);
        taDeskripsiViewMateri.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane6.setViewportView(taDeskripsiViewMateri);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Deskripsi");

        javax.swing.GroupLayout TampilkanMateriLayout = new javax.swing.GroupLayout(TampilkanMateri);
        TampilkanMateri.setLayout(TampilkanMateriLayout);
        TampilkanMateriLayout.setHorizontalGroup(
            TampilkanMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TampilkanMateriLayout.createSequentialGroup()
                .addGap(0, 144, Short.MAX_VALUE)
                .addGroup(TampilkanMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TampilkanMateriLayout.createSequentialGroup()
                        .addGroup(TampilkanMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TampilkanMateriLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(TampilkanMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TampilkanMateriLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel5)))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TampilkanMateriLayout.createSequentialGroup()
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(285, 285, 285))))
        );
        TampilkanMateriLayout.setVerticalGroup(
            TampilkanMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TampilkanMateriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(TampilkanMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TampilkanMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        Utama.add(TampilkanMateri, "card5");

        UpdateMateri.setBackground(new java.awt.Color(44, 120, 115));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(111, 185, 143));
        jLabel9.setText("Update Materi");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Nama Materi Baru");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Jumlah Bahasan Baru");

        tfUpdateMateri_NamaMateriBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUpdateMateri_NamaMateriBaruActionPerformed(evt);
            }
        });

        btnUpdateMateri.setText("Update");

        panel1.setBackground(new java.awt.Color(111, 185, 143));

        jScrollPane8.setViewportView(ListMateri_UpdateMateri);

        jScrollPane7.setViewportView(ListKelas_UpdateMateri);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Daftar Materi");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Daftar Kelas");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                        .addGap(24, 24, 24))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout UpdateMateriLayout = new javax.swing.GroupLayout(UpdateMateri);
        UpdateMateri.setLayout(UpdateMateriLayout);
        UpdateMateriLayout.setHorizontalGroup(
            UpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateMateriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UpdateMateriLayout.createSequentialGroup()
                        .addGroup(UpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(56, 56, 56)
                        .addGroup(UpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UpdateMateriLayout.createSequentialGroup()
                                .addComponent(tfUpdateMateri_NamaMateriBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(UpdateMateriLayout.createSequentialGroup()
                                .addComponent(tfUpdateMateri_jmlBahasanBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdateMateri)
                                .addGap(12, 12, 12)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateMateriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(306, 306, 306))
        );
        UpdateMateriLayout.setVerticalGroup(
            UpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateMateriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfUpdateMateri_NamaMateriBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfUpdateMateri_jmlBahasanBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateMateri))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Utama.add(UpdateMateri, "card6");

        DeleteMateri.setBackground(new java.awt.Color(44, 120, 115));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setText("Delete Materi");

        panel2.setBackground(new java.awt.Color(111, 185, 143));

        ListKelas_DeleteMateri.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane10.setViewportView(ListKelas_DeleteMateri);

        ListMateri_DeleteMateri.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane11.setViewportView(ListMateri_DeleteMateri);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Daftar Materi");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Daftar Kelas");

        btnDeleteMateri.setText("Delete");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeleteMateri)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(105, 105, 105)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteMateri)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout DeleteMateriLayout = new javax.swing.GroupLayout(DeleteMateri);
        DeleteMateri.setLayout(DeleteMateriLayout);
        DeleteMateriLayout.setHorizontalGroup(
            DeleteMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteMateriLayout.createSequentialGroup()
                .addGroup(DeleteMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteMateriLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteMateriLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel15)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        DeleteMateriLayout.setVerticalGroup(
            DeleteMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteMateriLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addGap(27, 27, 27)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        Utama.add(DeleteMateri, "card6");

        UpdateDataTentor.setBackground(new java.awt.Color(44, 120, 115));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Data Pribadi");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Update Data Pribadi");

        taDeskripsiUpdateProfile.setColumns(20);
        taDeskripsiUpdateProfile.setRows(5);
        taDeskripsiUpdateProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane13.setViewportView(taDeskripsiUpdateProfile);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Nama Baru Tentor");

        tfUpdateProfile_NamaTentor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.black, null, null));

        btnUpdateDataPribadi.setText("Update");
        btnUpdateDataPribadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDataPribadiActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setText("Update Profile");

        javax.swing.GroupLayout UpdateDataTentorLayout = new javax.swing.GroupLayout(UpdateDataTentor);
        UpdateDataTentor.setLayout(UpdateDataTentorLayout);
        UpdateDataTentorLayout.setHorizontalGroup(
            UpdateDataTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDataTentorLayout.createSequentialGroup()
                .addGroup(UpdateDataTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateDataTentorLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel19))
                    .addGroup(UpdateDataTentorLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(UpdateDataTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UpdateDataTentorLayout.createSequentialGroup()
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(UpdateDataTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(UpdateDataTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnUpdateDataPribadi)
                                        .addGroup(UpdateDataTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfUpdateProfile_NamaTentor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        UpdateDataTentorLayout.setVerticalGroup(
            UpdateDataTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDataTentorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(47, 47, 47)
                .addGroup(UpdateDataTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGroup(UpdateDataTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateDataTentorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateDataTentorLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUpdateProfile_NamaTentor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateDataPribadi)))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        Utama.add(UpdateDataTentor, "card8");

        javax.swing.GroupLayout LatarLayout = new javax.swing.GroupLayout(Latar);
        Latar.setLayout(LatarLayout);
        LatarLayout.setHorizontalGroup(
            LatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LatarLayout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(Utama, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        LatarLayout.setVerticalGroup(
            LatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LatarLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(Utama, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Latar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Latar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuLihatKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuLihatKelasActionPerformed
        Utama.removeAll();
        Utama.add(DaftarKelasSiswa);
        Utama.repaint();
        Utama.revalidate();
    }//GEN-LAST:event_btnMenuLihatKelasActionPerformed

    private void btnUpdateDataPribadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDataPribadiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateDataPribadiActionPerformed

    private void tfUpdateMateri_NamaMateriBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUpdateMateri_NamaMateriBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUpdateMateri_NamaMateriBaruActionPerformed

    private void btnMenuBuatMtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBuatMtrActionPerformed
        Utama.removeAll();
        Utama.add(Buat_materi);
        Utama.repaint();
        Utama.revalidate();
    }//GEN-LAST:event_btnMenuBuatMtrActionPerformed

    private void btnMenuTampilkanMtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuTampilkanMtrActionPerformed
        Utama.removeAll();
        Utama.add(TampilkanMateri);
        Utama.repaint();
        Utama.revalidate();
    }//GEN-LAST:event_btnMenuTampilkanMtrActionPerformed

    private void btnMenuUbahMtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuUbahMtrActionPerformed
        Utama.removeAll();
        Utama.add(UpdateMateri);
        Utama.repaint();
        Utama.revalidate();
    }//GEN-LAST:event_btnMenuUbahMtrActionPerformed

    private void btnMenuHapusMtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuHapusMtrActionPerformed
        Utama.removeAll();
        Utama.add(DeleteMateri);
        Utama.repaint();
        Utama.revalidate();
    }//GEN-LAST:event_btnMenuHapusMtrActionPerformed

    private void btnMenuUbahProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuUbahProfileActionPerformed
        Utama.removeAll();
        Utama.add(UpdateDataTentor);
        Utama.repaint();
        Utama.revalidate();
    }//GEN-LAST:event_btnMenuUbahProfileActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Utama.removeAll();
        Utama.add(Menu);
        Utama.repaint();
        Utama.revalidate();
        this.setVisible(false);
        resetTf();
        setDeskripsiKelasTentorString("");
        setDeskripsiViewMateriString("");
        setDeskripsiUpdateProfile("");
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        Utama.removeAll();
        Utama.add(Menu);
        Utama.repaint();
        Utama.revalidate();
        resetTf();
        setDeskripsiKelasTentorString("");
        setDeskripsiViewMateriString("");
        setDeskripsiUpdateProfile("");
    
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    java.awt.Panel Buat_materi;
    java.awt.Panel DaftarKelasSiswa;
    java.awt.Panel DeleteMateri;
    javax.swing.JLabel LabelWelcomTentor;
    java.awt.Panel Latar;
    javax.swing.JList<String> ListKelas_BuatMateri;
    javax.swing.JList<String> ListKelas_DaftarKelasSiswa;
    javax.swing.JList<String> ListKelas_DeleteMateri;
    javax.swing.JList<String> ListKelas_UpdateMateri;
    javax.swing.JList<String> ListKelas_ViewMateri;
    javax.swing.JList<String> ListMateri_DeleteMateri;
    javax.swing.JList<String> ListMateri_UpdateMateri;
    java.awt.Panel Menu;
    java.awt.Panel TampilkanMateri;
    java.awt.Panel UpdateDataTentor;
    java.awt.Panel UpdateMateri;
    java.awt.Panel Utama;
    javax.swing.JButton btnBack1;
    javax.swing.JButton btnBuatMateri;
    javax.swing.JButton btnDeleteMateri;
    javax.swing.JButton btnLogout;
    javax.swing.JButton btnMenuBuatMtr;
    javax.swing.JButton btnMenuHapusMtr;
    javax.swing.JButton btnMenuLihatKelas;
    javax.swing.JButton btnMenuTampilkanMtr;
    javax.swing.JButton btnMenuUbahMtr;
    javax.swing.JButton btnMenuUbahProfile;
    javax.swing.JButton btnUpdateDataPribadi;
    javax.swing.JButton btnUpdateMateri;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel12;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel15;
    javax.swing.JLabel jLabel16;
    javax.swing.JLabel jLabel17;
    javax.swing.JLabel jLabel18;
    javax.swing.JLabel jLabel19;
    javax.swing.JLabel jLabel21;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel9;
    javax.swing.JList<String> jList2;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JScrollPane jScrollPane10;
    javax.swing.JScrollPane jScrollPane11;
    javax.swing.JScrollPane jScrollPane13;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JScrollPane jScrollPane3;
    javax.swing.JScrollPane jScrollPane4;
    javax.swing.JScrollPane jScrollPane5;
    javax.swing.JScrollPane jScrollPane6;
    javax.swing.JScrollPane jScrollPane7;
    javax.swing.JScrollPane jScrollPane8;
    java.awt.Label label10;
    java.awt.Label label3;
    java.awt.Label label4;
    java.awt.Label label5;
    java.awt.Label label6;
    java.awt.Label label7;
    java.awt.Label label8;
    java.awt.Label label9;
    java.awt.List list1;
    java.awt.List list2;
    java.awt.Panel panel1;
    java.awt.Panel panel2;
    javax.swing.JPanel panelHeader;
    javax.swing.JTextArea taDeskripsiKelasTentor;
    javax.swing.JTextArea taDeskripsiUpdateProfile;
    javax.swing.JTextArea taDeskripsiViewMateri;
    javax.swing.JTextField tfBuatMateri_JmlBahasan;
    javax.swing.JTextField tfBuatMateri_NamaMateri;
    javax.swing.JTextField tfUpdateMateri_NamaMateriBaru;
    javax.swing.JTextField tfUpdateMateri_jmlBahasanBaru;
    javax.swing.JTextField tfUpdateProfile_NamaTentor;
    // End of variables declaration//GEN-END:variables

    ///MOUSE ADAPTER
    public void addMouseAdapter(MouseAdapter ma) {
        ListKelas_DaftarKelasSiswa.addMouseListener(ma);
        ListKelas_BuatMateri.addMouseListener(ma);
        ListKelas_ViewMateri.addMouseListener(ma);
        ListKelas_DeleteMateri.addMouseListener(ma);
        ListMateri_DeleteMateri.addMouseListener(ma);
        ListKelas_UpdateMateri.addMouseListener(ma);
        ListMateri_UpdateMateri.addMouseListener(ma);
    }

    //ACTION LISTENER
    public void addActionListener(ActionListener a1) {
        btnBack1.addActionListener(a1);
        btnMenuLihatKelas.addActionListener(a1);
        btnMenuBuatMtr.addActionListener(a1);
        btnMenuTampilkanMtr.addActionListener(a1);
        btnMenuUbahMtr.addActionListener(a1);
        btnMenuHapusMtr.addActionListener(a1);
        btnMenuUbahProfile.addActionListener(a1);
        btnUpdateDataPribadi.addActionListener(a1);
        btnUpdateMateri.addActionListener(a1);
        btnLogout.addActionListener(a1);
        btnDeleteMateri.addActionListener(a1);
        btnBuatMateri.addActionListener(a1);

    }
/////////LATAR

    public JButton getBtnBack() {
        return btnBack1;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }
    ///////GUI_DaftarKelasSiswa   

    public void setListKelas_DaftarKelasSiswa(String[] listKelasid) {
        ListKelas_DaftarKelasSiswa.setListData(listKelasid);
    }

    public JList getListKelas_DaftarKelasSiswa() {
        return ListKelas_DaftarKelasSiswa;
    }

    public String getSelectedListKelas_DaftarKelasSiswa() {
        return ListKelas_DaftarKelasSiswa.getSelectedValue();
    }

    public void setDeskripsiKelasTentorString(String s) {
        taDeskripsiKelasTentor.setText(s);
    }
    
    public void setLabelWelcome(String s){
        LabelWelcomTentor.setText(s);
    }
///////////BUAT MATERI

    public void setListKelas_BuatMateri(String[] listKelasid) {
        ListKelas_BuatMateri.setListData(listKelasid);
    }

    public JList getListKelas_BuatMateri() {
        return ListKelas_BuatMateri;
    }

    public String getSelectedListKelas_BuatMateri() {
        return ListKelas_BuatMateri.getSelectedValue();
    }

    public String getBuatMateri_NamaMateri() {
        return tfBuatMateri_NamaMateri.getText();
    }

    public int getBuatMateri_JmlBahasan() {
        return Integer.parseInt(tfBuatMateri_JmlBahasan.getText());
    }

    public JButton getBtnBuatMateri() {
        return btnBuatMateri;
    }
///////////Tampilkan Materi

    public void setListKelas_ViewMateri(String[] listKelasid) {
        ListKelas_ViewMateri.setListData(listKelasid);
    }

    public JList getListKelas_ViewMateri() {
        return ListKelas_ViewMateri;
    }

    public String getSelectedListKelas_ViewMateri() {
        return ListKelas_ViewMateri.getSelectedValue();
    }

    public void setDeskripsiViewMateriString(String s) {
        taDeskripsiViewMateri.setText(s);
    }
/////////// MENU

    public JButton getBtnMenuBuatMtr() {
        return btnMenuBuatMtr;
    }

    public JButton getBtnMenuHapusMtr() {
        return btnMenuHapusMtr;
    }

    public JButton getBtnMenuLihatKelas() {
        return btnMenuLihatKelas;
    }

    public JButton getBtnMenuTampilkanMtr() {
        return btnMenuTampilkanMtr;
    }

    public JButton getBtnMenuUbahMtr() {
        return btnMenuUbahMtr;
    }

    public JButton getBtnMenuUbahProfile() {
        return btnMenuUbahProfile;
    }
/////////// update materi

    public void setListKelas_UpdateMateri(String[] listKelasid) {
        ListKelas_UpdateMateri.setListData(listKelasid);
    }

    public JList getListKelas_UpdateMateri() {
        return ListKelas_UpdateMateri;
    }

    public String getSelectedListKelas_UpdateMateri() {
        return ListKelas_UpdateMateri.getSelectedValue();
    }

    public void setListMateri_UpdateMateri(String[] listKelasid) {
        ListMateri_UpdateMateri.setListData(listKelasid);
    }

    public JList getListMateri_UpdateMateri() {
        return ListMateri_UpdateMateri;
    }

    public String getSelectedListMateri_UpdateMateri() {
        return ListMateri_UpdateMateri.getSelectedValue();
    }

    

    public String getUpdateMateri_NamaMateriBaru() {
        return tfUpdateMateri_NamaMateriBaru.getText();
    }

    public int getUpdateMateri_jmlBahasanBaru() {
        return Integer.parseInt(tfUpdateMateri_jmlBahasanBaru.getText());
    }

    public JButton getBtnUpdateMateri() {
        return btnUpdateMateri;
    }

///////////DELETE MATERI
    public void setListKelas_DeleteMateri(String[] ListKelas_DeleteMateri) {
        this.ListKelas_DeleteMateri.setListData(ListKelas_DeleteMateri);
    }

    public JList getListKelas_DeleteMateri() {
        return ListKelas_DeleteMateri;
    }

    public String getSelectedListKelas_DeleteMateri() {
        return ListKelas_DeleteMateri.getSelectedValue();
    }

    public void setListMateri_DeleteMateri(String[] ListMateri_DeleteMateri) {
        this.ListMateri_DeleteMateri.setListData(ListMateri_DeleteMateri);
    }

    public JList getListMateri_DeleteMateri() {
        return ListMateri_DeleteMateri;
    }

    public String getSelectedListMateri_DeleteMateri() {
        return ListMateri_DeleteMateri.getSelectedValue();
    }

 

    public JButton getBtnDeleteMateri() {
        return btnDeleteMateri;
    }

//////////// UPDATE PROFILE
    public void setDeskripsiUpdateProfile(String s) {
        taDeskripsiUpdateProfile.setText(s);
    }

    public String getUpdateProfile_NamaTentor() {
        return tfUpdateProfile_NamaTentor.getText();
    }

    public JButton getBtnUpdateDataPribadi() {
        return btnUpdateDataPribadi;
    }
////////////// Reset TF    
    public void resetTf(){
        tfBuatMateri_NamaMateri.setText("");
        tfBuatMateri_JmlBahasan.setText("");
        tfUpdateMateri_NamaMateriBaru.setText("");
        tfUpdateMateri_jmlBahasanBaru.setText("");
        tfUpdateProfile_NamaTentor.setText("");
    }

}
