/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Afif Raihan
 */
public class NEW_GUI_ADMIN extends javax.swing.JFrame {
    
    GUI_Login viewLogin = new GUI_Login();
    
    /**
     * Creates new form NEW_GUI_LOGIN
     */
    public NEW_GUI_ADMIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        panelMoveLayout = new javax.swing.JPanel();
        panelMainMenu = new javax.swing.JPanel();
        panelChange = new javax.swing.JPanel();
        panelCreate = new javax.swing.JPanel();
        btnCreateKelas = new javax.swing.JButton();
        btnCreateTentor = new javax.swing.JButton();
        btnCreateMapel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelView = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnViewMapel = new javax.swing.JButton();
        btnViewTentor = new javax.swing.JButton();
        btnViewKelas = new javax.swing.JButton();
        btnViewKelasSiswaTentor = new javax.swing.JButton();
        btnViewSiswa = new javax.swing.JButton();
        btnViewMateriSetiapKelas = new javax.swing.JButton();
        panelUpdate = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnUpdateMapel = new javax.swing.JButton();
        btnUpdateKelas = new javax.swing.JButton();
        panelDelete = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnDeleteMapel = new javax.swing.JButton();
        btnDeleteKelas = new javax.swing.JButton();
        panelMenu = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panelAksiDeleteKelas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDeleteKelasDaftarKelas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDeleteKelasDeskripsiKelas = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnAksiDeleteKelas = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelAksiDeleteMapel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listDeleteMapelDaftarMapel = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        taDeleteMapelDeksripsiMapel = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        btnAksiDeleteMapel = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelAksiViewTentor = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        listViewTentorDaftarTentor = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        taViewTentorDetailTentor = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelAksiViewKelas = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        listViewKelasDaftarKelas = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        taViewKelasDeskripsiKelas = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panelAksiViewMapel = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        listViewMapelDaftarMapel = new javax.swing.JList<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        taViewMapelDeskripsiMapel = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        panelAksiViewSiswaKelasTentor = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        listViewSiswaKelasTentorDaftarKelas = new javax.swing.JList<>();
        jScrollPane14 = new javax.swing.JScrollPane();
        taViewSiswaKelasTentorDeskripsiKelas = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        panelAksiViewMateriKelas = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        listViewMateriKelasDaftarKelas = new javax.swing.JList<>();
        jScrollPane16 = new javax.swing.JScrollPane();
        taViewMateriKelasDetail = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        panelAksiViewSiswa = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        listViewSiswaDaftarSiswa = new javax.swing.JList<>();
        jScrollPane20 = new javax.swing.JScrollPane();
        taViewSiswaDetailSIswa = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        panelAksiUpdateMapel = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        listUpdateMapelDaftarMapel = new javax.swing.JList<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tfNamaMapelUpdateMapel = new javax.swing.JTextField();
        tfKkmUpdateMapel = new javax.swing.JTextField();
        tfJumlahBabUpdateMapel = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        javax.swing.JButton btnUpdateMapelUpdate = new javax.swing.JButton();
        labelStatusUpdate = new javax.swing.JLabel();
        panelAksiUpdateKelas = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        listUpdateKelasDaftarKelas = new javax.swing.JList<>();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        tfUpdateKelasNamaKelas = new javax.swing.JTextField();
        tfUpdateKelasMataPelajaran = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        btnUpdateKelasUpdate = new javax.swing.JButton();
        labelStatusUpdateKelas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(44, 120, 115));
        panelHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(111, 185, 143));
        jLabel1.setText("Halo Admin");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/exypnos1.png"))); // NOI18N

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 0));
        btnLogout.setText("LOGOUT");
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLogout.setBorderPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("HOME");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(213, 213, 213)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMoveLayout.setLayout(new java.awt.CardLayout());

        panelChange.setBackground(new java.awt.Color(111, 185, 143));
        panelChange.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelChange.setLayout(new java.awt.CardLayout());

        panelCreate.setBackground(new java.awt.Color(111, 185, 143));
        panelCreate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnCreateKelas.setText("KELAS");
        btnCreateKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateKelasActionPerformed(evt);
            }
        });

        btnCreateTentor.setText("TENTOR");
        btnCreateTentor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTentorActionPerformed(evt);
            }
        });

        btnCreateMapel.setText("MATA PELAJARAN");
        btnCreateMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMapelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("CREATE");

        javax.swing.GroupLayout panelCreateLayout = new javax.swing.GroupLayout(panelCreate);
        panelCreate.setLayout(panelCreateLayout);
        panelCreateLayout.setHorizontalGroup(
            panelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(panelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreateLayout.createSequentialGroup()
                        .addGroup(panelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCreateMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreateLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))))
            .addGroup(panelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreateLayout.createSequentialGroup()
                    .addContainerGap(54, Short.MAX_VALUE)
                    .addComponent(btnCreateTentor, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)))
        );
        panelCreateLayout.setVerticalGroup(
            panelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreateLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(btnCreateMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnCreateKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
            .addGroup(panelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCreateLayout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(btnCreateTentor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(477, Short.MAX_VALUE)))
        );

        panelChange.add(panelCreate, "card2");

        panelView.setBackground(new java.awt.Color(111, 185, 143));
        panelView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("VIEW");

        btnViewMapel.setText("MATA PELAJARAN");
        btnViewMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMapelActionPerformed(evt);
            }
        });

        btnViewTentor.setText("TENTOR");
        btnViewTentor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTentorActionPerformed(evt);
            }
        });

        btnViewKelas.setText("KELAS");
        btnViewKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewKelasActionPerformed(evt);
            }
        });

        btnViewKelasSiswaTentor.setText("KELAS-SISWA-TENTOR");
        btnViewKelasSiswaTentor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewKelasSiswaTentorActionPerformed(evt);
            }
        });

        btnViewSiswa.setText("SISWA");
        btnViewSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSiswaActionPerformed(evt);
            }
        });

        btnViewMateriSetiapKelas.setText("MATERI SETIAP KELAS");
        btnViewMateriSetiapKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMateriSetiapKelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewMateriSetiapKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewKelasSiswaTentor, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewLayout.createSequentialGroup()
                    .addContainerGap(36, Short.MAX_VALUE)
                    .addComponent(btnViewTentor, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)))
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(97, 97, 97)
                .addComponent(btnViewMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewKelasSiswaTentor, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewMateriSetiapKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelViewLayout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(btnViewTentor, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(498, Short.MAX_VALUE)))
        );

        panelChange.add(panelView, "card3");

        panelUpdate.setBackground(new java.awt.Color(111, 185, 143));
        panelUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("UPDATE");

        btnUpdateMapel.setText("MATA PELAJARAN");
        btnUpdateMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMapelActionPerformed(evt);
            }
        });

        btnUpdateKelas.setText("KELAS");
        btnUpdateKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateKelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUpdateLayout = new javax.swing.GroupLayout(panelUpdate);
        panelUpdate.setLayout(panelUpdateLayout);
        panelUpdateLayout.setHorizontalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelUpdateLayout.setVerticalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addGap(58, 58, 58)
                .addComponent(btnUpdateMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnUpdateKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(400, Short.MAX_VALUE))
        );

        panelChange.add(panelUpdate, "card4");

        panelDelete.setBackground(new java.awt.Color(111, 185, 143));
        panelDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelDelete.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setText("DELETE");

        btnDeleteMapel.setText("MATA PELAJARAN");
        btnDeleteMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMapelActionPerformed(evt);
            }
        });

        btnDeleteKelas.setText("KELAS");
        btnDeleteKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteKelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeleteLayout = new javax.swing.GroupLayout(panelDelete);
        panelDelete.setLayout(panelDeleteLayout);
        panelDeleteLayout.setHorizontalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeleteKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelDeleteLayout.setVerticalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addComponent(btnDeleteMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnDeleteKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        panelChange.add(panelDelete, "card5");

        panelMenu.setBackground(new java.awt.Color(111, 185, 143));
        panelMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnDelete.setBackground(new java.awt.Color(44, 120, 115));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(44, 120, 115));
        btnView.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(44, 120, 115));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("CREATE");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(44, 120, 115));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(44, 120, 115));
        jLabel3.setText("Welcome To Admin Page");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(69, 69, 69)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(139, 139, 139))
        );

        javax.swing.GroupLayout panelMainMenuLayout = new javax.swing.GroupLayout(panelMainMenu);
        panelMainMenu.setLayout(panelMainMenuLayout);
        panelMainMenuLayout.setHorizontalGroup(
            panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainMenuLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMainMenuLayout.setVerticalGroup(
            panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelChange, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelMoveLayout.add(panelMainMenu, "card4");

        panelAksiDeleteKelas.setBackground(new java.awt.Color(111, 185, 143));

        jScrollPane1.setViewportView(listDeleteKelasDaftarKelas);

        taDeleteKelasDeskripsiKelas.setColumns(20);
        taDeleteKelasDeskripsiKelas.setRows(5);
        jScrollPane2.setViewportView(taDeleteKelasDeskripsiKelas);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setText("DELETE KELAS");

        btnAksiDeleteKelas.setText("DELETE");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("DAFTAR KELAS");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("DESKRIPSI KELAS");

        javax.swing.GroupLayout panelAksiDeleteKelasLayout = new javax.swing.GroupLayout(panelAksiDeleteKelas);
        panelAksiDeleteKelas.setLayout(panelAksiDeleteKelasLayout);
        panelAksiDeleteKelasLayout.setHorizontalGroup(
            panelAksiDeleteKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAksiDeleteKelasLayout.createSequentialGroup()
                .addGroup(panelAksiDeleteKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAksiDeleteKelasLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAksiDeleteKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAksiDeleteKelasLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelAksiDeleteKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(panelAksiDeleteKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAksiDeleteKelasLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        panelAksiDeleteKelasLayout.setVerticalGroup(
            panelAksiDeleteKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAksiDeleteKelasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addGap(49, 49, 49)
                .addGroup(panelAksiDeleteKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAksiDeleteKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(btnAksiDeleteKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        panelMoveLayout.add(panelAksiDeleteKelas, "card3");

        panelAksiDeleteMapel.setBackground(new java.awt.Color(111, 185, 143));

        jScrollPane5.setViewportView(listDeleteMapelDaftarMapel);

        taDeleteMapelDeksripsiMapel.setColumns(20);
        taDeleteMapelDeksripsiMapel.setRows(5);
        jScrollPane6.setViewportView(taDeleteMapelDeksripsiMapel);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel14.setText("DELETE MATA PELAJARAN");

        btnAksiDeleteMapel.setText("DELETE");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("DAFTAR MATA PELAJARAN");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("DESKRIPSI MATA PELAJARAN");

        javax.swing.GroupLayout panelAksiDeleteMapelLayout = new javax.swing.GroupLayout(panelAksiDeleteMapel);
        panelAksiDeleteMapel.setLayout(panelAksiDeleteMapelLayout);
        panelAksiDeleteMapelLayout.setHorizontalGroup(
            panelAksiDeleteMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAksiDeleteMapelLayout.createSequentialGroup()
                .addGroup(panelAksiDeleteMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAksiDeleteMapelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAksiDeleteMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAksiDeleteMapelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelAksiDeleteMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(panelAksiDeleteMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAksiDeleteMapelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        panelAksiDeleteMapelLayout.setVerticalGroup(
            panelAksiDeleteMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAksiDeleteMapelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addGap(49, 49, 49)
                .addGroup(panelAksiDeleteMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAksiDeleteMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addGap(18, 18, 18)
                .addComponent(btnAksiDeleteMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        panelMoveLayout.add(panelAksiDeleteMapel, "card3");

        panelAksiViewTentor.setBackground(new java.awt.Color(111, 185, 143));

        jScrollPane7.setViewportView(listViewTentorDaftarTentor);

        taViewTentorDetailTentor.setColumns(20);
        taViewTentorDetailTentor.setRows(5);
        jScrollPane8.setViewportView(taViewTentorDetailTentor);

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel17.setText("VIEW TENTOR");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("DAFTAR TENTOR");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("DETAIL TENTOR");

        javax.swing.GroupLayout panelAksiViewTentorLayout = new javax.swing.GroupLayout(panelAksiViewTentor);
        panelAksiViewTentor.setLayout(panelAksiViewTentorLayout);
        panelAksiViewTentorLayout.setHorizontalGroup(
            panelAksiViewTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAksiViewTentorLayout.createSequentialGroup()
                .addGroup(panelAksiViewTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAksiViewTentorLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAksiViewTentorLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelAksiViewTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(panelAksiViewTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        panelAksiViewTentorLayout.setVerticalGroup(
            panelAksiViewTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAksiViewTentorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel17)
                .addGap(49, 49, 49)
                .addGroup(panelAksiViewTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAksiViewTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(jScrollPane8))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        panelMoveLayout.add(panelAksiViewTentor, "card3");

        panelAksiViewKelas.setBackground(new java.awt.Color(111, 185, 143));

        jScrollPane9.setViewportView(listViewKelasDaftarKelas);

        taViewKelasDeskripsiKelas.setColumns(20);
        taViewKelasDeskripsiKelas.setRows(5);
        jScrollPane10.setViewportView(taViewKelasDeskripsiKelas);

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel20.setText("VIEW KELAS");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("DAFTAR KELAS");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("DESKRIPSI KELAS");

        javax.swing.GroupLayout panelAksiViewKelasLayout = new javax.swing.GroupLayout(panelAksiViewKelas);
        panelAksiViewKelas.setLayout(panelAksiViewKelasLayout);
        panelAksiViewKelasLayout.setHorizontalGroup(
            panelAksiViewKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAksiViewKelasLayout.createSequentialGroup()
                .addGroup(panelAksiViewKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAksiViewKelasLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAksiViewKelasLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelAksiViewKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(panelAksiViewKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        panelAksiViewKelasLayout.setVerticalGroup(
            panelAksiViewKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAksiViewKelasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addGap(49, 49, 49)
                .addGroup(panelAksiViewKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAksiViewKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(jScrollPane10))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        panelMoveLayout.add(panelAksiViewKelas, "card3");

        panelAksiViewMapel.setBackground(new java.awt.Color(111, 185, 143));

        jScrollPane11.setViewportView(listViewMapelDaftarMapel);

        taViewMapelDeskripsiMapel.setColumns(20);
        taViewMapelDeskripsiMapel.setRows(5);
        jScrollPane12.setViewportView(taViewMapelDeskripsiMapel);

        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel23.setText("VIEW MATA PELAJARAN");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("DAFTAR MATA PELAJARAN");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("DESKRIPSI MATA PELAJARAN");

        javax.swing.GroupLayout panelAksiViewMapelLayout = new javax.swing.GroupLayout(panelAksiViewMapel);
        panelAksiViewMapel.setLayout(panelAksiViewMapelLayout);
        panelAksiViewMapelLayout.setHorizontalGroup(
            panelAksiViewMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAksiViewMapelLayout.createSequentialGroup()
                .addGroup(panelAksiViewMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAksiViewMapelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAksiViewMapelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelAksiViewMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(panelAksiViewMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        panelAksiViewMapelLayout.setVerticalGroup(
            panelAksiViewMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAksiViewMapelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel23)
                .addGap(49, 49, 49)
                .addGroup(panelAksiViewMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAksiViewMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(jScrollPane12))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        panelMoveLayout.add(panelAksiViewMapel, "card3");

        panelAksiViewSiswaKelasTentor.setBackground(new java.awt.Color(111, 185, 143));

        jScrollPane13.setViewportView(listViewSiswaKelasTentorDaftarKelas);

        taViewSiswaKelasTentorDeskripsiKelas.setColumns(20);
        taViewSiswaKelasTentorDeskripsiKelas.setRows(5);
        jScrollPane14.setViewportView(taViewSiswaKelasTentorDeskripsiKelas);

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel26.setText("VIEW SISWA-KELAS-TENTOR");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("DAFTAR KELAS");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("DESKRIPSI KELAS");

        javax.swing.GroupLayout panelAksiViewSiswaKelasTentorLayout = new javax.swing.GroupLayout(panelAksiViewSiswaKelasTentor);
        panelAksiViewSiswaKelasTentor.setLayout(panelAksiViewSiswaKelasTentorLayout);
        panelAksiViewSiswaKelasTentorLayout.setHorizontalGroup(
            panelAksiViewSiswaKelasTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAksiViewSiswaKelasTentorLayout.createSequentialGroup()
                .addGroup(panelAksiViewSiswaKelasTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAksiViewSiswaKelasTentorLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel26)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAksiViewSiswaKelasTentorLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelAksiViewSiswaKelasTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(panelAksiViewSiswaKelasTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        panelAksiViewSiswaKelasTentorLayout.setVerticalGroup(
            panelAksiViewSiswaKelasTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAksiViewSiswaKelasTentorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel26)
                .addGap(49, 49, 49)
                .addGroup(panelAksiViewSiswaKelasTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAksiViewSiswaKelasTentorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(jScrollPane14))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        panelMoveLayout.add(panelAksiViewSiswaKelasTentor, "card3");

        panelAksiViewMateriKelas.setBackground(new java.awt.Color(111, 185, 143));

        jScrollPane15.setViewportView(listViewMateriKelasDaftarKelas);

        taViewMateriKelasDetail.setColumns(20);
        taViewMateriKelasDetail.setRows(5);
        jScrollPane16.setViewportView(taViewMateriKelasDetail);

        jLabel29.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel29.setText("VIEW MATERI DAN KELAS");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("DAFTAR KELAS");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setText("DETAIL");

        javax.swing.GroupLayout panelAksiViewMateriKelasLayout = new javax.swing.GroupLayout(panelAksiViewMateriKelas);
        panelAksiViewMateriKelas.setLayout(panelAksiViewMateriKelasLayout);
        panelAksiViewMateriKelasLayout.setHorizontalGroup(
            panelAksiViewMateriKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAksiViewMateriKelasLayout.createSequentialGroup()
                .addGroup(panelAksiViewMateriKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAksiViewMateriKelasLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAksiViewMateriKelasLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelAksiViewMateriKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(panelAksiViewMateriKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        panelAksiViewMateriKelasLayout.setVerticalGroup(
            panelAksiViewMateriKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAksiViewMateriKelasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel29)
                .addGap(49, 49, 49)
                .addGroup(panelAksiViewMateriKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAksiViewMateriKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(jScrollPane16))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        panelMoveLayout.add(panelAksiViewMateriKelas, "card3");

        panelAksiViewSiswa.setBackground(new java.awt.Color(111, 185, 143));

        jScrollPane19.setViewportView(listViewSiswaDaftarSiswa);

        taViewSiswaDetailSIswa.setColumns(20);
        taViewSiswaDetailSIswa.setRows(5);
        jScrollPane20.setViewportView(taViewSiswaDetailSIswa);

        jLabel35.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel35.setText("VIEW SISWA");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("DAFTAR SISWA");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("DETAIL SISWA");

        javax.swing.GroupLayout panelAksiViewSiswaLayout = new javax.swing.GroupLayout(panelAksiViewSiswa);
        panelAksiViewSiswa.setLayout(panelAksiViewSiswaLayout);
        panelAksiViewSiswaLayout.setHorizontalGroup(
            panelAksiViewSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAksiViewSiswaLayout.createSequentialGroup()
                .addGroup(panelAksiViewSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAksiViewSiswaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAksiViewSiswaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelAksiViewSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(panelAksiViewSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        panelAksiViewSiswaLayout.setVerticalGroup(
            panelAksiViewSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAksiViewSiswaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel35)
                .addGap(49, 49, 49)
                .addGroup(panelAksiViewSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAksiViewSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(jScrollPane20))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        panelMoveLayout.add(panelAksiViewSiswa, "card3");

        panelAksiUpdateMapel.setBackground(new java.awt.Color(111, 185, 143));

        jScrollPane17.setViewportView(listUpdateMapelDaftarMapel);

        jLabel32.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel32.setText("UPDATE MATA PELAJARAN");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setText("DAFTAR MATA PELAJARAN");

        tfNamaMapelUpdateMapel.setEditable(false);

        tfKkmUpdateMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKkmUpdateMapelActionPerformed(evt);
            }
        });

        tfJumlahBabUpdateMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahBabUpdateMapelActionPerformed(evt);
            }
        });

        jLabel11.setText("NAMA MATA PELAJARAN");

        jLabel12.setText("JUMLAH BAB");

        jLabel13.setText("KKM");

        btnUpdateMapelUpdate.setText("UPDATE");
        btnUpdateMapelUpdate.setToolTipText("");

        labelStatusUpdate.setForeground(new java.awt.Color(255, 255, 0));
        labelStatusUpdate.setText("STATUS UPDATE");

        javax.swing.GroupLayout panelAksiUpdateMapelLayout = new javax.swing.GroupLayout(panelAksiUpdateMapel);
        panelAksiUpdateMapel.setLayout(panelAksiUpdateMapelLayout);
        panelAksiUpdateMapelLayout.setHorizontalGroup(
            panelAksiUpdateMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAksiUpdateMapelLayout.createSequentialGroup()
                .addGroup(panelAksiUpdateMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAksiUpdateMapelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAksiUpdateMapelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelAksiUpdateMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAksiUpdateMapelLayout.createSequentialGroup()
                                .addComponent(labelStatusUpdate)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelAksiUpdateMapelLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(490, 794, Short.MAX_VALUE))
                            .addGroup(panelAksiUpdateMapelLayout.createSequentialGroup()
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelAksiUpdateMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAksiUpdateMapelLayout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addGroup(panelAksiUpdateMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNamaMapelUpdateMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfKkmUpdateMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfJumlahBabUpdateMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAksiUpdateMapelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUpdateMapelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(270, 270, 270)))))))
                .addGap(22, 22, 22))
        );
        panelAksiUpdateMapelLayout.setVerticalGroup(
            panelAksiUpdateMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAksiUpdateMapelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel32)
                .addGap(49, 49, 49)
                .addComponent(jLabel33)
                .addGroup(panelAksiUpdateMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAksiUpdateMapelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAksiUpdateMapelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNamaMapelUpdateMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfJumlahBabUpdateMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfKkmUpdateMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnUpdateMapelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(labelStatusUpdate)
                .addContainerGap())
        );

        panelMoveLayout.add(panelAksiUpdateMapel, "card3");

        panelAksiUpdateKelas.setBackground(new java.awt.Color(111, 185, 143));

        jScrollPane18.setViewportView(listUpdateKelasDaftarKelas);

        jLabel38.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel38.setText("UPDATE KELAS");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setText("DAFTAR KELAS");

        tfUpdateKelasNamaKelas.setEditable(false);

        jLabel40.setText("NAMA KELAS");

        jLabel41.setText("MATA PELAJARAN");

        btnUpdateKelasUpdate.setText("UPDATE");
        btnUpdateKelasUpdate.setToolTipText("");

        labelStatusUpdateKelas.setForeground(new java.awt.Color(255, 255, 0));
        labelStatusUpdateKelas.setText("STATUS UPDATE");

        javax.swing.GroupLayout panelAksiUpdateKelasLayout = new javax.swing.GroupLayout(panelAksiUpdateKelas);
        panelAksiUpdateKelas.setLayout(panelAksiUpdateKelasLayout);
        panelAksiUpdateKelasLayout.setHorizontalGroup(
            panelAksiUpdateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAksiUpdateKelasLayout.createSequentialGroup()
                .addGroup(panelAksiUpdateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAksiUpdateKelasLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAksiUpdateKelasLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelAksiUpdateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAksiUpdateKelasLayout.createSequentialGroup()
                                .addComponent(labelStatusUpdateKelas)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelAksiUpdateKelasLayout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(490, 889, Short.MAX_VALUE))
                            .addGroup(panelAksiUpdateKelasLayout.createSequentialGroup()
                                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelAksiUpdateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAksiUpdateKelasLayout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addGroup(panelAksiUpdateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfUpdateKelasNamaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfUpdateKelasMataPelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel40)
                                            .addComponent(jLabel41))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAksiUpdateKelasLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUpdateKelasUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(278, 278, 278)))))))
                .addGap(22, 22, 22))
        );
        panelAksiUpdateKelasLayout.setVerticalGroup(
            panelAksiUpdateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAksiUpdateKelasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel38)
                .addGap(49, 49, 49)
                .addComponent(jLabel39)
                .addGroup(panelAksiUpdateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAksiUpdateKelasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAksiUpdateKelasLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfUpdateKelasNamaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfUpdateKelasMataPelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnUpdateKelasUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(labelStatusUpdateKelas)
                .addContainerGap())
        );

        panelMoveLayout.add(panelAksiUpdateKelas, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelMoveLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(658, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(panelMoveLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        panelChange.removeAll();
        panelChange.add(panelView);
        panelChange.repaint();
        panelChange.revalidate();
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        panelChange.removeAll();
        panelChange.add(panelDelete);
        panelChange.repaint();
        panelChange.revalidate();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        panelChange.removeAll();
        panelChange.add(panelCreate);
        panelChange.repaint();
        panelChange.revalidate();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        panelChange.removeAll();
        panelChange.add(panelUpdate);
        panelChange.repaint();
        panelChange.revalidate();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tfKkmUpdateMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKkmUpdateMapelActionPerformed
        panelMoveLayout.removeAll();
        panelMoveLayout.add(panelMainMenu);
        panelMoveLayout.repaint();
        panelMoveLayout.revalidate();
    }//GEN-LAST:event_tfKkmUpdateMapelActionPerformed

    private void tfJumlahBabUpdateMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahBabUpdateMapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJumlahBabUpdateMapelActionPerformed

    private void btnCreateKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateKelasActionPerformed
//        panelChange.removeAll();
//        panelChange.add(panelCreate);
//        panelChange.repaint();
//        panelChange.revalidate();
    }//GEN-LAST:event_btnCreateKelasActionPerformed

    private void btnCreateTentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTentorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateTentorActionPerformed

    private void btnCreateMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateMapelActionPerformed

    private void btnViewMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMapelActionPerformed
        panelMoveLayout.removeAll();
        panelMoveLayout.add(panelAksiViewMapel);
        panelMoveLayout.repaint();
        panelMoveLayout.revalidate();
    }//GEN-LAST:event_btnViewMapelActionPerformed

    private void btnViewTentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTentorActionPerformed
        panelMoveLayout.removeAll();
        panelMoveLayout.add(panelAksiViewTentor);
        panelMoveLayout.repaint();
        panelMoveLayout.revalidate();
    }//GEN-LAST:event_btnViewTentorActionPerformed

    private void btnViewKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewKelasActionPerformed
        panelMoveLayout.removeAll();
        panelMoveLayout.add(panelAksiViewKelas);
        panelMoveLayout.repaint();
        panelMoveLayout.revalidate();
    }//GEN-LAST:event_btnViewKelasActionPerformed

    private void btnViewKelasSiswaTentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewKelasSiswaTentorActionPerformed
        panelMoveLayout.removeAll();
        panelMoveLayout.add(panelAksiViewSiswaKelasTentor);
        panelMoveLayout.repaint();
        panelMoveLayout.revalidate();
    }//GEN-LAST:event_btnViewKelasSiswaTentorActionPerformed

    private void btnViewSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSiswaActionPerformed
        panelMoveLayout.removeAll();
        panelMoveLayout.add(panelAksiViewSiswa);
        panelMoveLayout.repaint();
        panelMoveLayout.revalidate();
    }//GEN-LAST:event_btnViewSiswaActionPerformed

    private void btnViewMateriSetiapKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMateriSetiapKelasActionPerformed
        panelMoveLayout.removeAll();
        panelMoveLayout.add(panelAksiViewMateriKelas);
        panelMoveLayout.repaint();
        panelMoveLayout.revalidate();
    }//GEN-LAST:event_btnViewMateriSetiapKelasActionPerformed

    private void btnUpdateMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMapelActionPerformed
        panelMoveLayout.removeAll();
        panelMoveLayout.add(panelAksiUpdateMapel);
        panelMoveLayout.repaint();
        panelMoveLayout.revalidate();
    }//GEN-LAST:event_btnUpdateMapelActionPerformed

    private void btnUpdateKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateKelasActionPerformed
        panelMoveLayout.removeAll();
        panelMoveLayout.add(panelAksiUpdateKelas);
        panelMoveLayout.repaint();
        panelMoveLayout.revalidate();
    }//GEN-LAST:event_btnUpdateKelasActionPerformed

    private void btnDeleteMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMapelActionPerformed
        panelMoveLayout.removeAll();
        panelMoveLayout.add(panelAksiDeleteMapel);
        panelMoveLayout.repaint();
        panelMoveLayout.revalidate();
    }//GEN-LAST:event_btnDeleteMapelActionPerformed

    private void btnDeleteKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteKelasActionPerformed
        panelMoveLayout.removeAll();
        panelMoveLayout.add(panelAksiDeleteKelas);
        panelMoveLayout.repaint();
        panelMoveLayout.revalidate();
    }//GEN-LAST:event_btnDeleteKelasActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        panelMoveLayout.removeAll();
        panelMoveLayout.add(panelMainMenu);
        panelMoveLayout.repaint();
        panelMoveLayout.revalidate();
    }//GEN-LAST:event_btnBackActionPerformed

    
    public void addActionListener(ActionListener a1){
        btnCreate.addActionListener(a1);
        btnCreateKelas.addActionListener(a1);
        btnCreateMapel.addActionListener(a1);
        btnCreateTentor.addActionListener(a1);
        btnDelete.addActionListener(a1);
        btnDeleteKelas.addActionListener(a1);
        btnDeleteMapel.addActionListener(a1);
        btnUpdate.addActionListener(a1);
        btnUpdateKelas.addActionListener(a1);
        btnUpdateMapel.addActionListener(a1);
        btnView.addActionListener(a1);
        btnViewKelas.addActionListener(a1);
        btnViewKelasSiswaTentor.addActionListener(a1);
        btnViewMapel.addActionListener(a1);
        btnViewMateriSetiapKelas.addActionListener(a1);
        btnViewSiswa.addActionListener(a1);
        btnViewTentor.addActionListener(a1);
        btnLogout.addActionListener(a1);
    }

    public JButton getBtnCreate() {
        return btnCreate;
    }

    public JButton getBtnCreateKelas() {
        return btnCreateKelas;
    }

    public JButton getBtnCreateMapel() {
        return btnCreateMapel;
    }

    public JButton getBtnCreateTentor() {
        return btnCreateTentor;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public JButton getBtnDeleteKelas() {
        return btnDeleteKelas;
    }

    public JButton getBtnDeleteMapel() {
        return btnDeleteMapel;
    }

    public JButton getBtnUpdate() {
        return btnUpdate;
    }

    public JButton getBtnUpdateKelas() {
        return btnUpdateKelas;
    }

    public JButton getBtnUpdateMapel() {
        return btnUpdateMapel;
    }

    public JButton getBtnView() {
        return btnView;
    }

    public JButton getBtnViewKelas() {
        return btnViewKelas;
    }

    public JButton getBtnViewKelasSiswaTentor() {
        return btnViewKelasSiswaTentor;
    }

    public JButton getBtnViewMapel() {
        return btnViewMapel;
    }

    public JButton getBtnViewMateriSetiapKelas() {
        return btnViewMateriSetiapKelas;
    }

    public JButton getBtnViewSiswa() {
        return btnViewSiswa;
    }

    public JButton getBtnViewTentor() {
        return btnViewTentor;
    }

    public JButton getjBtnLogout() {
        return btnLogout;
    }

    public JPanel getPanelChange() {
        return panelChange;
    }

    public JPanel getPanelCreate() {
        return panelCreate;
    }

    public JPanel getPanelDelete() {
        return panelDelete;
    }

    public JPanel getPanelHeader() {
        return panelHeader;
    }

    public JPanel getPanelMenu() {
        return panelMenu;
    }

    public JPanel getPanelUpdate() {
        return panelUpdate;
    }

    public JPanel getPanelView() {
        return panelView;
    }
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAksiDeleteKelas;
    private javax.swing.JButton btnAksiDeleteMapel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateKelas;
    private javax.swing.JButton btnCreateMapel;
    private javax.swing.JButton btnCreateTentor;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteKelas;
    private javax.swing.JButton btnDeleteMapel;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateKelas;
    private javax.swing.JButton btnUpdateKelasUpdate;
    private javax.swing.JButton btnUpdateMapel;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnViewKelas;
    private javax.swing.JButton btnViewKelasSiswaTentor;
    private javax.swing.JButton btnViewMapel;
    private javax.swing.JButton btnViewMateriSetiapKelas;
    private javax.swing.JButton btnViewSiswa;
    private javax.swing.JButton btnViewTentor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel labelStatusUpdate;
    private javax.swing.JLabel labelStatusUpdateKelas;
    private javax.swing.JList<String> listDeleteKelasDaftarKelas;
    private javax.swing.JList<String> listDeleteMapelDaftarMapel;
    private javax.swing.JList<String> listUpdateKelasDaftarKelas;
    private javax.swing.JList<String> listUpdateMapelDaftarMapel;
    private javax.swing.JList<String> listViewKelasDaftarKelas;
    private javax.swing.JList<String> listViewMapelDaftarMapel;
    private javax.swing.JList<String> listViewMateriKelasDaftarKelas;
    private javax.swing.JList<String> listViewSiswaDaftarSiswa;
    private javax.swing.JList<String> listViewSiswaKelasTentorDaftarKelas;
    private javax.swing.JList<String> listViewTentorDaftarTentor;
    private javax.swing.JPanel panelAksiDeleteKelas;
    private javax.swing.JPanel panelAksiDeleteMapel;
    private javax.swing.JPanel panelAksiUpdateKelas;
    private javax.swing.JPanel panelAksiUpdateMapel;
    private javax.swing.JPanel panelAksiViewKelas;
    private javax.swing.JPanel panelAksiViewMapel;
    private javax.swing.JPanel panelAksiViewMateriKelas;
    private javax.swing.JPanel panelAksiViewSiswa;
    private javax.swing.JPanel panelAksiViewSiswaKelasTentor;
    private javax.swing.JPanel panelAksiViewTentor;
    private javax.swing.JPanel panelChange;
    private javax.swing.JPanel panelCreate;
    private javax.swing.JPanel panelDelete;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMainMenu;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMoveLayout;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JPanel panelView;
    private javax.swing.JTextArea taDeleteKelasDeskripsiKelas;
    private javax.swing.JTextArea taDeleteMapelDeksripsiMapel;
    private javax.swing.JTextArea taViewKelasDeskripsiKelas;
    private javax.swing.JTextArea taViewMapelDeskripsiMapel;
    private javax.swing.JTextArea taViewMateriKelasDetail;
    private javax.swing.JTextArea taViewSiswaDetailSIswa;
    private javax.swing.JTextArea taViewSiswaKelasTentorDeskripsiKelas;
    private javax.swing.JTextArea taViewTentorDetailTentor;
    private javax.swing.JTextField tfJumlahBabUpdateMapel;
    private javax.swing.JTextField tfKkmUpdateMapel;
    private javax.swing.JTextField tfNamaMapelUpdateMapel;
    private javax.swing.JTextField tfUpdateKelasMataPelajaran;
    private javax.swing.JTextField tfUpdateKelasNamaKelas;
    // End of variables declaration//GEN-END:variables
}
